name: Playwright Tests
on:
    workflow_dispatch:
        inputs:
            apps:
                type: choice
                description: "Which env to run tests against"
                required: true
                default: "production"
                options:
                    - "development"
                    - "staging"
                    - "production"
jobs:
    test:
        timeout-minutes: 60
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Install pnpm
              uses: pnpm/action-setup@v4
              with:
                version: 9

            - uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: 'pnpm'

            - name: Install dependencies
              run: pnpm i --frozen-lockfile

            - name: Install Playwright Browsers
              run: npx playwright install --with-deps
            - name: Test
              run: cd tests
            - name: LS
              run: ls

            #- name: Run Playwright tests
            #  env:
            #    MALOU_E2E_PASSWORD: ${{ secrets.MALOU_E2E_PASSWORD }}
            #    GMAIL_PASSWORD: ${{ secrets.GMAIL_PASSWORD }}
            #    ENV: ${{ github.event.inputs.apps }}
            #  run: npx playwright test

            #- name: Create report directory with unique name
            #  run: mkdir -p playwright-report/${{ github.run_id }}

            #- name: Move report to unique directory
            #  run: mv playwright-report/* playwright-report/${{ github.run_id }}

            #- uses: actions/upload-artifact@v4
            #  if: ${{ !cancelled() }}
            #  with:
            #      name: playwright-report-${{ github.run_id }}
            #      path: playwright-report/${{ github.run_id }}
            #      retention-days: 5
                  
            #- name: Deploy report to GitHub Pages
            #  uses: peaceiris/actions-gh-pages@v4
            #  if: ${{ always() }}
            #  with:
            #      github_token: ${{ secrets.GITHUB_TOKEN }}
            #      publish_dir: playwright-report
